#!/usr/bin/env ruby
require 'rubygems'
require 'logger'
require 'highline/system_extensions'
require 'colorize'
require 'yaml'

include HighLine::SystemExtensions

class ListElement
  attr_reader :task, :created_at, :done
  attr_writer :done

  def initialize(task)
    @is_done = false
    @task = task.chomp
    @created_at = Time.now
  end
end

class Command
  attr_reader :shortcut, :desc, :ask

  def initialize(shortcut, desc, ask=nil)
    @shortcut, @desc, @ask = shortcut, desc, ask
  end
end

class TodoManager
  VERSION = '0.0.0'
  COMMANDS = [Command.new('k', :key_up),
              Command.new('j', :key_down),
              Command.new('a', :add_task, 'Enter the task: '),
              Command.new('s', :add_subtask, 'Enter the subtask: '),
              Command.new('x', :toggle_task),
              Command.new('d', :delete_task, 'Delete? [yN]: '),
              Command.new('q', :quit, 'Quit? [yN]: ')]

  def initialize(config=nil)
    @config = load_config(config) unless config.nil?
    @list = [ListElement.new("Drink coffee"), ListElement.new("Buy milk"), ListElement.new("Check out Sugar cafe")]
    @current = 0
    @num_tasks = 0
  end

  def main()
    clear_screen()
    loop do
      cmd = get_character
      run_cmd(cmd)
    end
  end

  private

    def load_config(config)
      YAML.load_file(config)
    end

    def clear_screen()
      system('clear')
    end

    def run_cmd(sc)
      command = COMMANDS.find { |c| c.shortcut == sc.chr }
      return if command.nil?
      print_list(command.ask)
      case command.desc
      when :key_up
        @current -= 1 unless @current.zero?
      when :key_down
        @current += 1 unless @current == @list.length - 1
      when :toggle_task
        el = @list[@current]
        el.done = !el.done
      when :add_task
        task = STDIN.readline.chomp
        @list << ListElement.new(task) unless task == ''
      when :add_subtask
        subtask = STDIN.readline.chomp
        return unless subtask == ''
      when :delete_task
        @list.delete_at(@current) if STDIN.readline.chomp == 'y'
      when :quit
        if STDIN.readline.chomp == 'y'
          puts 'Exiting!'
          exit(0)
        end
      end
      clear_screen()
      print_list()
    end

    def print_list(ask=nil)
      puts ' '*50
      print_header()
      @list.each_with_index do |el, i|
        print_el(el, @current == i)
      end
      if @list.empty?
        puts "No tasks found."
      end
      print_footer()
      puts ' '*50
      print ask unless ask.nil?
      STDOUT.flush
    end

    def print_el(el, current)
      task = el.task
      out = ''
      out << checkbox(el) + ' '
      if current
        out << format_current(task)
      else
        out << task
      end
      puts out + ' '*(50-out.length)
    end

    def print_header()
      banner = " TodoManager (v.#{VERSION}) "
      out = ''
      num_dashes = (50 - banner.length)/2
      out << '-'*num_dashes
      out << "#{banner.colorize(:color => :black, :background => :white)}"
      out << '-'*(50 - (banner.length + num_dashes))
      puts out
    end

    def print_footer()
      puts '-'*50
      COMMANDS.each do |c|
        puts "[#{c.shortcut}] #{c.desc.to_s.gsub('_', ' ').capitalize}"
      end
      puts '-'*50
    end

    def format_current(str)
      str.colorize(:background => :red)
    end

    def checkbox(el)
      if el.done then '[X]' else '[ ]' end
    end
end

if $0 == __FILE__
  manager = TodoManager.new()
  ret = manager.main()
  begin
    exit(ret)
  rescue TypeError
    exit(0)
  end
end